name: Multi-Environment Deployment

on:
  push:
    branches: [ main, staging, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Deployment Variables
        id: vars
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "DEPLOY_PATH=/home/ubuntu/aqwaya" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "PORT_WAITLIST=3001" >> $GITHUB_ENV
            echo "PORT_FRONTEND=3000" >> $GITHUB_ENV
            echo "PORT_BACKEND=5000" >> $GITHUB_ENV
            echo "API_URL=https://aqwaya.com" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            echo "DEPLOY_PATH=/home/ubuntu/aqwaya-staging" >> $GITHUB_ENV
            echo "BRANCH=staging" >> $GITHUB_ENV
            echo "PORT_WAITLIST=3501" >> $GITHUB_ENV
            echo "PORT_FRONTEND=3500" >> $GITHUB_ENV
            echo "PORT_BACKEND=5001" >> $GITHUB_ENV
            echo "API_URL=https://staging.aqwaya.com" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=/home/ubuntu/aqwaya-dev" >> $GITHUB_ENV
            echo "BRANCH=dev" >> $GITHUB_ENV
            echo "PORT_WAITLIST=4001" >> $GITHUB_ENV
            echo "PORT_FRONTEND=4000" >> $GITHUB_ENV
            echo "PORT_BACKEND=5002" >> $GITHUB_ENV
            echo "API_URL=https://dev.aqwaya.com" >> $GITHUB_ENV
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BRANCH, DEPLOY_PATH, PORT_BACKEND, PORT_WAITLIST, PORT_FRONTEND, API_URL
          script: |
            cd ${{ env.DEPLOY_PATH }}
            git fetch origin
            git reset --hard origin/${{ env.BRANCH }}

            cd backend
            npm install
            npx prisma generate
            npm run build
            pm2 delete backend-${{ env.BRANCH }} || true
            PORT=${{ env.PORT_BACKEND }} pm2 start dist/src/main.js --name backend-${{ env.BRANCH }}

            cd ../waitlist
            npm install
            export NEXT_PUBLIC_API_URL=${{ env.API_URL }}
            npm run build
            pm2 restart waitlist-${{ env.BRANCH }} --update-env || pm2 start npm --name waitlist-${{ env.BRANCH }} -- start -- -p ${{ env.PORT_WAITLIST }}

            cd ../frontend
            npm install 
            
            sed -i "/basePath:/d" next.config.mjs
            sed -i "/trailingSlash:/d" next.config.mjs
            
            export NEXT_FONT_GOOGLE_MOCKED=true
            export NEXT_PUBLIC_API_URL=${{ env.API_URL }}
            npm run build 
            
            pm2 restart frontend-${{ env.BRANCH }} --update-env || pm2 start npm --name frontend-${{ env.BRANCH }} -- start -- -p ${{ env.PORT_FRONTEND }}
            
            pm2 save