name: Deploy Aqwaya-FE-Staging on the Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd /var/www/aqwayai/frontend/dev.aqwaya.com
            git pull origin main
            npm install
            npm run build
            pm2 restart dev.aqwaya.com
            sudo systemctl reload nginx
