name: Deploy Aqwaya-main to the Server
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    name: Deploy to the Server
    runs-on: ubuntu-latest
 
    steps:
      - name: Update and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 18.212.219.109
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: | 
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
 
            cd /var/www/aqwaya/frontend
            git checkout dev
            git pull origin dev
            npm i
            npm run build
            pm2 restart tisl-app
            pm2 save

            sudo systemctl reload nginx
